AllCops:
  TargetRubyVersion: 2.5.1
  Include:
    - ./*.conf
    - ./Gemfile
    - ./Guardfile
    - ./Rakefile
    - tasks/*.rake
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - !ruby/regexp /bin\/(?:(?!trema).)*$/

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/DotPosition:
  EnforcedStyle: trailing
