Feature: Switch Event forwarding configuration command (`delete_forward_entry`)
  
  Switch Event forwarding configuration command (`delete_forward_entry`)
  is a command to delete a event forwarding entry from 
  Switch Manager and Switch Daemons.
  
  Configuring event forwarding entry on a Switch Daemon will change 
  where the event of specified type will be forwarded to
  on the specified Switch.
  
  Configuring event forwarding entry on a Switch Manager will change 
  where the event of specified type will be forwarded to
  on the all newly connected Switch after configuration.
  
  This command may be useful when: 
  * Remove previousely added controller which was mirroring events for debugging purpose.
  
  Note that this command will only change where each event is forwarded, 
  and it will **not** emulate any switch events, which normally occurs when a 
  controller is newly connected to a switch, etc.
  * swich_ready event will **not** be generated by adding a entry to existing switch.
  * disconnected event will **not** be generated by removing a entry from existing switch.

  This command is also a simple usage example for event_forward_interface.h C API.

  Background: 
    Given I cd to "../../src/examples/switch_event_config/"
    Given I compile "delete_forward_entry.c" into "delete_forward_entry"
    Given I compile "dump_forward_entries.c" into "dump_forward_entries"

  Scenario: delete_forward_entry Usage
    When I run `trema run './delete_forward_entry -h'`
    Then the output should contain:
      """
      Delete OpenFlow Switch Manager/Daemon event forward entry.
       Both Switch Mgr/Daemon: delete_forward_entry -t EVENT_TYPE service_name
       Only Switch Manager   : delete_forward_entry -m -t EVENT_TYPE service_name
       Only Switch Daemon    : delete_forward_entry -s SWITCH_DPID -t EVENT_TYPE service_name
      
       EVENT_TYPE:
        -t, --type={vendor,packet_in,port_status,state_notify} Specify event type.
      """

  Scenario Outline: Delete 'RepeaterHub' from All Switch Manager/Daemon's event forward configuration for packet_in
    Given a file named "nw_dsl.conf" with:
      """
        vswitch { datapath_id 0x1 }
        vswitch { datapath_id 0x2 }
      """
    And I run `trema run ../repeater_hub/repeater-hub.rb -c nw_dsl.conf -d`
    And wait until "RepeaterHub" is up
    When I run `trema run './delete_forward_entry -t packet_in RepeaterHub '`
    Then the output should contain "Operation Succeeded."
    Then I run `trema run './dump_forward_entries <option> -t packet_in'`
    Then the output should not match /Current service name list:.*  RepeaterHub/

    Examples: 
      | target | option |
      | SW MGR | -m     |
      | SW 0x1 | -s 0x1 |
      | SW 0x2 | -s 0x2 |

  Scenario Outline: Delete 'RepeaterHub' only from Switch Manager's event forward configuration for packet_in
    Given a file named "nw_dsl.conf" with:
      """
        vswitch { datapath_id 0x1 }
        vswitch { datapath_id 0x2 }
      """
    And I run `trema run ../repeater_hub/repeater-hub.rb -c nw_dsl.conf -d`
    And wait until "RepeaterHub" is up
    When I run `trema run './delete_forward_entry -m -t packet_in RepeaterHub'`
    Then the output should contain "Updated service name list is empty."
    Then the output should not contain "  RepeaterHub"
    Then I run `trema run './dump_forward_entries -s <switch> -t packet_in'`
    Then the output should match /Current service name list:.*  RepeaterHub/

    Examples: 
      | switch |
      | 0x1    |
      | 0x2    |

  Scenario Outline: Delete 'RepeaterHub' only from Switch Daemon 0x1's event forward configuration for packet_in
    Given a file named "nw_dsl.conf" with:
      """
        vswitch { datapath_id 0x1 }
        vswitch { datapath_id 0x2 }
      """
    And I run `trema run ../repeater_hub/repeater-hub.rb -c nw_dsl.conf -d`
    And wait until "RepeaterHub" is up
    When I run `trema run './delete_forward_entry -s 0x1 -t packet_in RepeaterHub'`
    Then the output should contain "Updated service name list is empty."
    Then the output should not contain "  RepeaterHub"
    Then I run `trema run './dump_forward_entries <option> -t packet_in'`
    Then the output should match /Current service name list:.*  RepeaterHub/

    Examples: 
      | target | option |
      | SW MGR | -m     |
      | SW 0x2 | -s 0x2 |

